name: Auto Update Bing Images CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout
    - name: checkout
      uses: actions/checkout@v2
    # setup nodejs
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: node ./assets/js/bing.js
    # commit
    - name: Deploy to Github Pages
      env:
        GIT_NAME: Cx330-502
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/Cx330-502/Cx330-502.github.io
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        touch CNAME && echo 'cx330-502.top' > CNAME
        git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:master
